### ISSUE TITLE
Build issue caused by use of deprecated/unavailable dependency repository

### ISSUE THREAD

**Issue by eingruenesbeb** [OopsieWoopsie/Spicord#73]
Hey, I'm writing this, because the latest build over on [jitpack](https://jitpack.io/#Spicord/Spicord) has failed, because of an issue with one of the dependencies' repository.
Specifically the issue is with the repository for Velocity, as "https://repo.velocitypowered.com/snapshots/" is deprecated and no longer available. It should be replaced with "https://repo.papermc.io/repository/maven-public/", as stated on [the PaperMC Discord-server](https://discord.com/channels/289587909051416579/1077385604012179486/1080730104717643776).

**Comment by anvorgesa** [comment]
Hi, thank you for reporting the issue, please use tag `v5-SNAPSHOT` (which already was built by jitpack) as the artifactId as stated on the README.md 
I will update the pom.xml on next upcoming changes on this plugin, thanks again for noticing. :smile:

**Comment by eingruenesbeb** [comment]
Is there an ETA for the update? I can't build my project, without this issue being resolved:
![grafik](https://user-images.githubusercontent.com/63373786/231099904-277045ff-809a-4f32-ad3a-2de944b0d4f4.png)

![grafik](https://user-images.githubusercontent.com/63373786/231100570-2f8f42a6-5ef5-486a-8278-bc0ebdff5290.png)

**Comment by anvorgesa** [comment]
Hello, I have used the GitHub web editor to update the URL, I have no idea if that fixes the issue or not as at the moment I do not have access to my PC in order to make a test build, maybe the change will be reflected in jitpack soon.

**Comment by eingruenesbeb** [comment]
I've made a fork and am currently testing as well. I may make a pull request soon™.

**Comment by anvorgesa** [comment]
The build failed again in jitpack, I have changed the velocity version to one I know is in the new repo

**Comment by anvorgesa** [comment]
Looks like it is having an issue with bungeecord now :thinking: uhg

**Comment by anvorgesa** [comment]
It worked! Again thank you for reporting this and I'm so sorry I have not had time to fix this before and for causing you troubles with your project build. Have a nice day ^^

**Comment by eingruenesbeb** [comment]
No worries ^^
Great, that it works now and thanks for fixing this.

**Comment by eingruenesbeb** [comment]
For the future, may I suggest the following Github workflow:
```yml
# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "v5" ]
  pull_request:
    branches: [ "v5" ]
  # Automatically run every week on Sunday at 0:00 AM UTC
  schedule: 
   - cron: "0 0 * * SUN"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
```
