### ISSUE TITLE
Startup error on Velocity 3.4.0

### ISSUE THREAD

**Issue by bakkbone** [OopsieWoopsie/Spicord#92]
If an addon is enabled/disabled via command, the `config.toml` is being improperly set - `command_support` and `command_prefix` are replaced by the command with `commandSupport` and `commandPrefix`, causing this issue on start: https://mclo.gs/nS2u5nb

`config.toml` immediately after running `/sp bot default add motd`, causing the above startup error as logged:

```toml
# +--------------------------------------------------+
# | Project: Spicord                                 |
# | GitHub: https://github.com/OopsieWoopsie/Spicord |
# +--------------------------------------------------+

loadDelay = 10
integratedAddonFooter = "Powered by Spicord v{version}"

[[bots]]
  name = "default"
  enabled = true
  token = "<redacted>"
  initialCommandCleanup = true
  commandSupport = true
  commandPrefix = "!"
  addons = [
    "spicord::info",
    "spicord::plugins",
    "spicord::players",
    "huskchat",
    "motd"
  ]

[jdaLogging]
  enabled = true
  debug = false
```

Corrected `config.toml` that allowed the plugin to function as intended:

```toml
# +--------------------------------------------------+
# | Project: Spicord                                 |
# | GitHub: https://github.com/OopsieWoopsie/Spicord |
# +--------------------------------------------------+

loadDelay = 10
integratedAddonFooter = "Powered by Spicord v{version}"

[[bots]]
  name = "default"
  enabled = true
  token = "<redacted>"
  initialCommandCleanup = true
  command_support = true
  command_prefix = "!"
  addons = [
    "spicord::info",
    "spicord::plugins",
    "spicord::players",
    "huskchat",
    "motd"
  ]

[jdaLogging]
  enabled = true
  debug = false
```
